// index.js
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import dynamic from 'next/dynamic'

const inter = Inter({ subsets: ['latin'] })

// Dynamically import the PlotlyComponent
const PlotlyComponentWithDropDown = dynamic(() => import('./PlotlyComponentWithDropDown'), { ssr: false })
const HeatMapComponent = dynamic(() => import('./HeatMapComponent'), { ssr: false });
const ScatterComponent = dynamic(() => import('./ScatterComponent'), { ssr: false });
const BubbleChartDescriptionComponent = dynamic(() => import('./descriptions/BubbleChartDescriptionComponent'), {ssr: false});
const ScatterDescriptionComponent = dynamic(() => import('./descriptions/ScatterDescriptionComponent'), {ssr: false});
const HeatmapDescriptionComponent = dynamic(() => import('./descriptions/HeatmapDescriptionComponent'), {ssr: false});
const ScatterMatrixComponent = dynamic(() => import('./ScatterMatrixComponent'), { ssr: false });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description} style={{  width: '100%', marginBottom: '4%', textAlign: 'center', fontSize: '28px', maxWidth: 'none'}}>
          <h1>Education’s role in a country’s development indicators</h1>
        </div>
        <div className="bubble-container">
          <BubbleChartDescriptionComponent />
          <PlotlyComponentWithDropDown />
        </div>
        <br/>
        <br/>
        <div className="bubble-container">
          <ScatterDescriptionComponent />
          <ScatterComponent />
        </div>
        <br/>
        <br/>
        <div className="bubble-container">
          <HeatmapDescriptionComponent />
          <HeatMapComponent />
        </div>
        <br/>
        {/* <ScatterMatrixComponent/> Render the Scatter Component */}
      </main>
    </>
  )
}